spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inte
    username: root
    password: fan4620.
    druid:
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      aop-patterns: com.han.boot02.admin.*

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
      filters: stat,wall
  redis:
    host: 192.168.153.128
    port: 6379
    password: fan4620.
#    timeout: 500
    #client-type: jedis #客户端类型设置为jedis
#    client-type: lettuce
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: 8
#        max-idle: 8
#        min-idle: 0
#    client-name: root
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0



#mybatis
mybatis:
  mapper-locations: classpath:mapper/*
  type-aliases-package: com.han.shiro_spring_boot.bean

